### ISSUE TITLE
Feature Proposal: Attach HowLong to a running process

### ISSUE THREAD

**Issue by rkrp** [mattjegan/HowLong#17]
Can we have a feature to attach to an already running process and give timing stats about that? 

I regularly come across this scenario when I am running heavy resource intensive processes [say Linux kernel compilation or Android AOSP builds or downloading system updates]. It is fairly easy to forget running the command under `howlong` or *nix's `time` while launching the process. It would be great to keep track of how long something has been running even after it has been started. 

I have a fairly solid knowledge of achieving that in Linux systems with `proc` support. Not sure about other operating systems, though. 

Would love to hear your thoughts about this.

**Comment by mattjegan** [comment]
Yeah, I think this would be a great feature. A simple flag to attach the process would be good. Perhaps we could just supply the process id?

**Comment by rkrp** [comment]
Yeah. I think we can make use of [psutil](https://github.com/giampaolo/psutil) library to do that. That will make sure that our solution is cross-platform. Also, how would we be displaying the running time? Printing each and every line per second (or N seconds) would soon make it cluttered. I am thinking something along of [this line](https://stackoverflow.com/questions/4897359/output-to-the-same-line-overwriting-previous-output-python-2-5).

@mattjegan what do you say?

**Comment by mattjegan** [comment]
Yeah `psutil` looks fine to me. With the running time, I like the idea of the single line but perhaps we should add that as a new flag? My reasoning is incase any current users are expecting the multi-line output that we currently have. We may decide to switch to make the single line a default in a future release perhaps. Is this enough info for you to get started @rkrp ?

**Comment by rkrp** [comment]
Agreed. It is a good idea to let the users pass a flag if they are interested in single-line output. 

Will most probably be working on this, this weekend.

**Comment by mattjegan** [comment]
Sounds good, sorry for the late go ahead. Looking forward to your PR.

**Comment by mattjegan** [comment]
Hey @rkrp , are you still happy to work on this?

**Comment by mattjegan** [comment]
Labelling as help wanted if anyone wants to jump on this. @rkrp let me know if you still want it.

**Comment by rkrp** [comment]
Apologies for the late reply. Unfortuantely, I'll not be able to work on this for at least another month. I think it's best if someone else picks it up.

**Comment by mattjegan** [comment]
No worries, this issue is now up for grabs.

**Comment by kennethgoodman** [comment]
I wrote the code, but can't for the life of me figure out why I don't have access to push the code/create PR/create branch

**Comment by kennethgoodman** [comment]
Created a PR to add this:

terminal 1:
```
$ping -c 500 google.com
```

Terminal 2:
```
$ pgrep ping
94608
$ python HowLong.py -l DEBUG -i 5 pid 94608
```

**Comment by mattjegan** [comment]
@kennethgoodman can I assign this to yourself until it's closed?

**Comment by kennethgoodman** [comment]
Yes
