### ISSUE TITLE
Add colors to output

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/HowLong#20]
It would be nice to have some color in our output.

**Comment by abhyudaypratap** [comment]
i would like to take this up.

How can I start?

**Comment by mattjegan** [comment]
Awesome, thanks for the enthusiasm. We'd probably want to start by using the [crayons package](https://github.com/kennethreitz/crayons) and stripping out our `red` function and replacing that with calls to `crayons.yellow` (yellow doesn't seem as DANGEROUS as red).

This means that we can then use `crayons.red` for all our assert messages and perhaps `crayons.greed` for the start and finish text. 

Thanks again for putting up your hand and please don't hesitate to ask me if you need help.

**Comment by yalanyali** [comment]
I'd suggest [colorama ](https://github.com/tartley/colorama) module for a cross-platform solution. Windows does not support ANSI sequences by default, so they need to get converted to win32 calls. Colorama is able to do just that. Good luck.

**Comment by emorres25** [comment]
Can I also work on this?

**Comment by mattjegan** [comment]
@yalanyali that is a good point about colorama being cross-platform and hence I think we should go with that. A solution to using crayons on windows is discussed [here](https://github.com/kennethreitz/crayons/issues/4) through the use of `colorama.init()` but I think we can look at that later if we really want the crayons syntax to work.

**Comment by mattjegan** [comment]
By all means @emorres25 if @abhyudaypratap decides they can't work on this anymore (I need to give first-person-in a chance) then you can pick it up. If you are looking for other work on this project however, please feel free to look at the current issues and/or suggest features or find bugs locally. I'll see if I can find some more things you can work on and I'll put them in the issue tracker.

**Comment by ZacharyLangley** [comment]
I'd like to work on this, how would i start? I've done a lot of design work on top of development. So I feel like this is right up my alley.

**Comment by mattjegan** [comment]
@ZacharyLangley my apologies, this issue should have been closed as it is now completed in #24 . If you'd be interested in adding to the project, we are currently looking for feature requests as per #9
