### ISSUE TITLE
Get code health to 100%

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/HowLong#5]
All you need to do is fix this code smell: https://landscape.io/github/mattjegan/HowLong/5/messages/smell

**Comment by lucasloisp** [comment]
I can try this out later today, if you agree. Aren't there any more code smells? Is the HowLong class definition the only one to fix?

**Comment by mattjegan** [comment]
Hey @lucasloisp , that'd be great 😄  it's the only one that I see coming up on landscape, when you've made the change submit a pull request and I'll approve it for you. Thanks.

**Comment by mattjegan** [comment]
Hey @lucasloisp ,sorry but I didn't realise the change had already been made earlier and landscape hadn't updated the code health so you won't need to do the work. If I find any more issues I'd be happy for you to try pick them up if you'd like. Thanks again 😄

**Comment by lucasloisp** [comment]
I see. Well, I'll look out for other issues. Thanks anyways!
